version: '3.7'

volumes:
  pgdata:

networks:
  app-tier:
    driver: bridge

services:
  logic_app:
    build:
      context: src
      dockerfile: logic_app/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - app-tier
    volumes:
      - type: bind
        source: ./src/logic_app
        target: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5001", "--reload"]
    environment:
      - HOST_CARD_DETECTOR=${HOST_CARD_DETECTOR}
      - HOST_TEXT_DETECTOR=${HOST_TEXT_DETECTOR}
      - HOST_TEXT_OCR=${HOST_TEXT_OCR}
      - CARD_ALIGN__BASEIMG_PATH=${CARD_ALIGN__BASEIMG_PATH}
      - CARD_ALIGN__PER_MATCH=${CARD_ALIGN__PER_MATCH}

  model_deployed:
    build:
      context: src
      dockerfile: model_deployed/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-tier
    volumes:
      - type: bind
        source: ./src/model_deployed
        target: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    environment:
      # Card Detector Settings
      - CARD_DETECTOR__MODEL_PATH=${CARD_DETECTOR__MODEL_PATH}
      - CARD_DETECTOR__CONF=${CARD_DETECTOR__CONF}
      
      # Card Align Settings
      - CARD_ALIGN__BASEIMG_PATH=${CARD_ALIGN__BASEIMG_PATH}
      - CARD_ALIGN__PER_MATCH=${CARD_ALIGN__PER_MATCH}
      
      # Text Detector Settings
      - TEXT_DETECTOR__MODEL_PATH=${TEXT_DETECTOR__MODEL_PATH}
      - TEXT_DETECTOR__CONF=${TEXT_DETECTOR__CONF}
      
      # Text OCR Settings
      - TEXT_OCR__CONFIG_NAME=${TEXT_OCR__CONFIG_NAME}
      - TEXT_OCR__DEVICE=${TEXT_OCR__DEVICE}
      - TEXT_OCR__MODEL_PATH=${TEXT_OCR__MODEL_PATH}
      - TEXT_OCR__CNN_PRETRAINED=${TEXT_OCR__CNN_PRETRAINED}
      - TEXT_OCR__VOCAB=${TEXT_OCR__VOCAB}

      - CARD_ALIGN__BASEIMG_PATH=${CARD_ALIGN__BASEIMG_PATH}
      - CARD_ALIGN__PER_MATCH=${CARD_ALIGN__PER_MATCH}